class Routes {
  static const splash = '/splash';
  static const login = '/login';
  static const register = '/register';
  static const home = '/home';
  static const user = '/user';
  static const profile = '/profile';
  static const users = '/users';
  static const userDetail = '/users/:id';
  static const ponche = '/ponche';
  static const poncheHistorial = '/ponche/historial';
  static const catalogo = '/catalogo';
  static const contabilidad = '/contabilidad';
  static const contabilidadCierresDiarios = '/contabilidad/cierres-diarios';
  static const contabilidadDepositos = '/contabilidad/depositos-bancarios';
  static const contabilidadFacturaFiscal = '/contabilidad/factura-fiscal';
  static const contabilidadPagosPendientes = '/contabilidad/pagos-pendientes';
  static const clientes = '/clientes';
  static const ventas = '/ventas';
  static const cotizaciones = '/cotizaciones';
  static const cotizacionesHistorial = '/cotizaciones/historial';
  static const serviceOrders = '/service-orders';
  static const serviceOrderCommissions = '/service-orders/commissions';
  static const mediaGallery = '/media-gallery';
  static const serviceOrderCreate = '/service-orders/nueva';
  static const serviceOrderDetail = '/service-orders/:id';
  static const documentFlows = '/document-flows';
  static const documentFlowDetail = '/document-flows/:orderId';
  static const registrarVenta = '/ventas/nueva';
  static const clienteNuevo = '/clientes/nuevo';
  static const clientesMapa = '/clientes/mapa';
  static const clienteDetalle = '/clientes/:id';
  static const clienteEditar = '/clientes/:id/editar';
  static const ai = '/ia';
  static const nomina = '/nomina';
  static const misPagos = '/mis-pagos';
  static const manualInterno = '/manual-interno';
  static const configuracion = '/configuracion';
  static const administracion = '/administracion';
  static const administracionPonches = '/administracion/ponches';
  static const administracionVentas = '/administracion/ventas';
  static const administracionCotizaciones = '/administracion/cotizaciones';

  static String clienteDetail(String id) => '/clientes/$id';
  static String clienteEdit(String id) => '/clientes/$id/editar';
  static String serviceOrderById(String id) => '/service-orders/$id';
  static String documentFlowByOrderId(String orderId) =>
      '/document-flows/$orderId';
}
